

export const ENUM_ADMIN_ROLE = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
}

export const ENUM_ADMIN_PERMISSION = {
  USER: "USER",
  BLOCK_USER: "BLOCK_USER",
  DELETE_USER: "DELETE_USER",
  VIEW_USER: "VIEW_USER",

  LISTING: "LISTING",
  VIEW_LISTING: "VIEW_LISTING",
  APPROVE_LISTING: "APPROVED_LISTING",
  REJECTE_LISTING: "REJECTED_LISTING",
  DELETE_LISTING: "DELETE_LISTING",
  ADD_METADATA: "ADD_METADATA",   
  EDIT_LISTING: "EDIT_LISTING",

  EARNING: "EARNING",
  TOTAL_EARNING: "TOTAL_EARNING",
  EARNING_GROWTH_CHART: "EARNING_GROWTH_CHART",
  TRANSACTION_HISTORY: "TRANSACTION_HISTORY",

  CATEGORY: "CATEGORY",
  EDIT_CATEGORY: "EDIT_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  ADD_CATEGORY: "ADD_CATEGORY",

  COUPON: "COUPON",
  ADD_COUPON: "ADD_COUPON",
  EDIT_COUPON: "EDIT_COUPON",
  DELETE_COUPON: "DELETE_COUPON",
  
  BLOG: "BLOG",
  ADD_BLOG: "ADD_BLOG",
  EDIT_BLOG: "EDIT_BLOG",
  DELETE_BLOG: "DELETE_BLOG",

  FAQ: "FAQ",
  ADD_FAQ: "ADD_FAQ",
  EDIT_FAQ: "EDIT_FAQ",
  DELETE_FAQ: "DELETE_FAQ",

  SUBSCRIPTION: "SUBSCRIPTION",
  EDIT_PRICE: "EDIT_PRICE",
  EDIT_FEATURE: "EDIT_FEATURE",

  SUBSCRIBER_LIST: "SUBSCRIBER_LIST",
  NDA: "NDA",

  PRIVACY_POLICY: "PRIVACY_POLICY",
  TERMS_CONDITIONS: "TERMS_CONDITIONS",
  REFUND_POLICY: "REFUND_POLICY",
}
