

export const ENUM_ADMIN_ROLE = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
}


export const ENUM_ADMIN_PERMISSION = {
  USER: "USER",
  LISTING: "LISTING",
  EARNING: "EARNING",
  CATEGORY: "CATEGORY",
  SUBSCRIPTION: "SUBSCRIPTION",
  COUPON: "COUPON",
  BLOG: "BLOG",
  NDA: "NDA",
  FAQ: "FAQ",
  PRIVACY_POLICY: "PRIVACY_POLICY",
  TERMS_CONDITIONS: "TERMS_CONDITIONS",
  REFUND_POLICY: "REFUND_POLICY"
}
